import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal.module.css";

export const metadata: Metadata = {
  title: "Privacy Policy",
};

export default function PrivacyPage() {
  return (
    <main className={styles.main}>
      <Link href="/" className={styles.back}>
        ← Back to home
      </Link>

      <h1 className={styles.title}>Privacy Policy</h1>
      <p className={styles.updated}>Last updated: August 19, 2026</p>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Overview</h2>
        <p>
          Second Helpings is a personal recipe-sharing project built as a
          portfolio piece to demonstrate web development skills. It is not a
          commercial product. This policy explains what information the site
          collects when you use it and how that information is handled.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Information we collect</h2>
        <ul className={styles.list}>
          <li>
            <strong>Account data:</strong> when you register, we collect a
            username, an email address, and a password (stored only as a
            secure hash using bcrypt).
          </li>
          <li>
            <strong>Content you create:</strong> recipes, ratings, comments,
            bookmarks, and notification preferences.
          </li>
          <li>
            <strong>Technical data:</strong> cookies used to keep you signed
            in (login tokens). These are session-based and are cleared when
            you log out or after a period of inactivity. The site does not
            run analytics or advertising trackers.
          </li>
        </ul>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>How we use it</h2>
        <p>
          Your data is used only to run the service: to authenticate you, to
          save and display your recipes, ratings, comments, and bookmarks,
          and to let you manage your own content. We do not sell or rent your
          information to anyone.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Third parties</h2>
        <p>The project uses a few third-party services to work:</p>
        <ul className={styles.list}>
          <li>
            Recipe data and photos are provided by{" "}
            <a
              className={styles.link}
              href="https://www.themealdb.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              TheMealDB
            </a>
            .
          </li>
          <li>
            Some original recipe content on the site is generated by the site
            administrator using Google&apos;s Gemini API. This is separate
            from user-submitted recipes, which are created by users and
            reviewed by admins before being published.
          </li>
          <li>
            Hosting and database services store the data listed above on
            servers operated by the provider used to deploy the app.
          </li>
        </ul>
        <p>
          These services have their own privacy policies, which we recommend
          reviewing if you have concerns.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Data retention</h2>
        <p>
          Your content is retained for as long as your account is active.
          When you delete a recipe, comment, or other content, it&apos;s
          removed from the live database immediately. When you delete your
          account, associated personal data is removed from the live
          database; residual copies may persist briefly in routine backups
          before being cycled out.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Children</h2>
        <p>
          This site is not directed at children under 13, and we do not
          knowingly collect personal information from children.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Your rights</h2>
        <p>
          You can view and delete the content you create at any time from
          within the site. If you&apos;d like to delete your account or have
          questions about your data, please open an issue in the
          project&apos;s GitHub repository. Note that GitHub issues are
          public, so please don&apos;t include your password, full name, or
          other sensitive details in the issue itself - a username and a
          brief description of the request is enough for it to be actioned.
          Requests are typically handled within a few days, as this is a
          small, independently maintained project.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>About this project</h2>
        <p>
          Second Helpings is a demonstration project created for portfolio
          purposes. It is not operated as a commercial service, and this
          policy is not legal advice. If this project is ever used with real
          user data at scale, this policy should be reviewed by a legal
          professional to ensure it meets applicable requirements (e.g.,
          GDPR, CCPA).
        </p>
      </section>
    </main>
  );
}