import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal.module.css";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <main className={styles.main}>
      <Link href="/" className={styles.back}>
        ← Back to home
      </Link>

      <h1 className={styles.title}>Terms of Service</h1>
      <p className={styles.updated}>Last updated: August 19, 2026</p>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>About this project</h2>
        <p>
          Second Helpings is a personal project built as a portfolio piece,
          letting you browse recipes and, if you create an account, save your
          own recipes, rate and comment on others, and bookmark the ones you
          like. It is not operated as a commercial service. By using the site,
          you agree to these terms.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Accounts</h2>
        <ul className={styles.list}>
          <li>You are responsible for keeping your login details safe.</li>
          <li>Please provide accurate account details when registering.</li>
          <li>
            One person should use one account; the site is not intended for
            bot or automated use.
          </li>
          <li>
            We reserve the right to suspend or remove accounts that violate
            these terms.
          </li>
        </ul>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Your content</h2>
        <p>
          Recipes and comments you post remain yours, but you grant the site
          permission to display them as part of the service. You confirm that
          the content you post is yours (or that you&apos;re allowed to post
          it) and that it doesn&apos;t violate the rights of others.
        </p>
        <p>Do not post content that is unlawful, offensive, or spam.</p>
        <p>
          Moderators may review, unpublish, or remove content that violates
          these terms, and may suspend accounts for repeated or serious
          violations.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Recipe disclaimer</h2>
        <p>
          Recipes are shared for informational purposes only and are provided
          &ldquo;as is.&rdquo; They are not professional, medical, or
          allergen-safety advice. Always check ingredients yourself,
          especially if you have allergies or dietary requirements, and cook
          at your own risk.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Third-party and AI-generated content</h2>
        <p>
          Some recipes and photos are provided by{" "}
          <a
            className={styles.link}
            href="https://www.themealdb.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            TheMealDB
          </a>
          . Some original recipe content is generated by the site
          administrator using Google&apos;s Gemini API. The site is not
          affiliated with TheMealDB, Google, or any other third-party source,
          and is not responsible for the accuracy of content they provide.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Availability</h2>
        <p>
          This is an independently maintained personal project. The site may
          be modified, interrupted, or discontinued at any time, with or
          without notice.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Liability</h2>
        <p>
          The service is provided without warranties of any kind. To the
          fullest extent permitted by law, the operator is not liable for any
          damages arising from use of the site or reliance on its content.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Changes to these terms</h2>
        <p>
          These terms may be updated from time to time. Continued use of the
          site after changes are posted means you accept the updated terms.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Contact</h2>
        <p>
          Questions about these terms, or requests related to your account or
          content, can be raised by opening an issue in the project&apos;s
          GitHub repository. Since issues are public, please don&apos;t
          include sensitive personal details - a brief description of the
          request is enough.
        </p>
      </section>
    </main>
  );
}